# get partial effects data

################################################################################
# This script contains code to obtain data on the partial effects of predictor
# variables from the categorical random forests, as well as the partial effects
# of those variables dependent on values of another variable. These data can be
# used to produce partial effects plots, partial dependene plots, and partial
# effects contour plots. 
#
# Author: Rohan Boone
################################################################################

# SETUP

# We use the R package randomForestSRC (Ishwaran & Kogular, 2025)
# https://cran.r-project.org/package=randomForestSRC.
# install.packages("randomForestSRC")
library(randomForestSRC)

# *SPECIFY OUTPUT DIRECTORY* #
outdir <- "" # do not put a / at the end of the directory
dir.exists(outdir)

# *SPECIFY SPECIES* #
species <- "QUDG"
# load the random forest objects generated by rf_run.R. We use the climate-only
# models for this analysis
load(paste0("rf_objects/", species, "_rf3d.R"))
load(paste0("rf_objects/", species, "_rf5d.R"))

################################################################################
# GET PARTIAL EFFECTS DATA
     
# specify variable of interest for partial effects
# *SPECIFY VARIABLE* #
var1 <- "ppt0cold"

# obtain subsample of the variable from the low-growth model
var1Low <- sort(sample(unique(mod3d$xvar[[var1]]), 400))
# run partial random forest on var1 using the variable subsample to get the
# partial effect of var1 at various levels on predicting low growth
var1LowPartial <- partial.rfsrc(mod3d, partial.xvar = var1, 
                               partial.values = var1Low)
# convert data to plottable format and save
var1LowPlotdata <- get.partial.plot.data(var1LowPartial)
save(var1LowPlotdata, file = paste0(outdir, "/", species, "_", var1,
                                    "_plotdata_low.R"))

# obtain subsample of the variable from the high-growth model
var1High <- sort(sample(unique(mod5d$xvar[[var1]]), 400))
# run parital rf on var1 using the variable subsample to get the partial effect
# of var1 at various levels on predicting high growth
var1HighPartial <- partial.rfsrc(mod5d, partial.xvar = var1,
                                partial.values = var1High)
# convert to plottable format and save
var1HighPlotdata <- get.partial.plot.data(var1HighPartial)
save(var1HighPlotdata, file = paste0(outdir, "/", species, "_", var1,
                                     "_plotdata_high.R"))

################################################################################
# GET PARTIAL DEPENDENCE DATA

# the partial effect of var1 dependent on values of what variable?
# *SPECIFY VARIABLE* #
var2 <- "vpdMax0cold"

# LOW-GROWTH

# pull low and high values from var2 data using quantile
var2Low <- quantile((mod3d$xvar[[var2]]), probs = c(0.025, 0.975))
# calculate partial effect of var1 given high and low values of var2
pdataLow <- do.call(rbind, lapply(var2Low, function(x2) {
  o <- randomForestSRC::partial(mod3d,
                                partial.xvar = var1, partial.xvar2 = var2,
                                partial.values = var1Low, partial.values2 = x2)
  cbind(var1Low, x2, get.partial.plot.data(o)$yhat)
}))
# manipulate the data
pdataLow <- data.frame(pdataLow)
colnames(pdataLow) <- c("var1", "var2", "effectsize")
pdataLow[,2] <- factor(pdataLow[,2])
levels(pdataLow[,2]) <- c("Low", "High")
# save to avoidre-running the last section
save(pdataLow, file = paste0(outdir, "/", species, "_", var1, "_x_", var2,
                             "_plotdata_low.R"))

# get data into plottable format
var1LowPlotdata <- data.frame(cbind(var1 = pdataLow[1:400, "var1"],
                                    var2 = "All",
                                    effectsize = var1LowPlotdata[["yhat"]]))
var1LowPlotdata[,1] <- as.numeric(var1LowPlotdata[,1])
var1LowPlotdata[,2] <- factor(var1LowPlotdata[,2])
var1LowPlotdata[,3] <- as.numeric(var1LowPlotdata[,3])
var1LowPlotdata2 <- rbind(pdataLow, var1LowPlotdata)
# and save again - this is the final, eventually plottable, object
save(var1LowPlotdata2, file = paste0(outdir, "/", species, "_", var1, "_x_", var2,
                                    "_plotdata_all_low.R"))

# HIGH-GROWTH

# pull low and high values of var 2 using quantile
var2High <- quantile((mod5d$xvar[[var2]]), probs = c(0.025, 0.975))
# calculate partial effect of var1 given high and low values of var2
pdataHigh <- do.call(rbind, lapply(var2High, function(x2) {
  o <- randomForestSRC::partial(mod5d,
                                partial.xvar = var1, partial.xvar2 = var2,
                                partial.values = var1High, partial.values2 = x2)
  cbind(var1High, x2, get.partial.plot.data(o)$yhat)
}))
# manipulate the data
pdataHigh <- data.frame(pdataHigh)
colnames(pdataHigh) <- c("var1", "var2", "effectsize")
pdataHigh[,2] <- factor(pdataHigh[,2])
levels(pdataHigh[,2]) <- c("Low", "High")
# save to avoidre-running the last section
save(pdataHigh, file = paste0(outdir, "/", species, "_", var1, "_x_", var2,
                              "_plotdata_high.R"))

# get data into a plottable format
var1HighPlotdata <- data.frame(cbind(var1 = pdataHigh[1:400, "var1"],
                                     var2 = "All",
                                     effectsize = var1HighPlotdata[["yhat"]]))
var1HighPlotdata[,1] <- as.numeric(var1HighPlotdata[,1])
var1HighPlotdata[,2] <- factor(var1HighPlotdata[,2])
var1HighPlotdata[,3] <- as.numeric(var1HighPlotdata[,3])
var1HighPlotdata2 <- rbind(pdataHigh, var1HighPlotdata)
# and save again
save(var1HighPlotdata2, file = paste0(outdir, "/", species, "_", var1, "_x_", var2,
                                     "_plotdata_all_high.R"))
