This folder is meant to store R objects generated by the random forest analysis (class RFSRC).
These files are too large to store remotely on github and should be stored in the local repo
only, hence the .gitinore

Example code is provided for one species (QUDG); the code should be easily adapted to apply to data for other species.
